### ISSUE TITLE
Missing arrows in isomorphism post

### ISSUE THREAD

**Issue by ThreeFx** [Arkham/juliu.is#7]
Hey, great post you wrote!

I think you are missing two `-> c` arrows in the following block, after showing that `curry` and `uncurry` are isomorphic:

> After looking at the type signatures again we can say that these following functions are isomorphic:

```
((a, b) -> c) -> a -> b
(a -> b -> c) -> (a, b)
```

**Comment by Arkham** [comment]
Hey @ThreeFx, glad you enjoyed it! Great catch, I'll fix it asap :)

**Comment by Arkham** [comment]
Fixed in 395955d, thanks again!
